[program:process-refunds]
directory=/var/www
command=php bin/console messenger:consume process_refunds --env=prod
autostart=true
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
